config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # ルートパスの設定
  root to: "prototypes#index"
  # prototypesのパス
  resources :prototypes, only: [:new, :create, :show, :edit, :update, :destroy] do
    # commentsのパス
    resources :comments, only: [ :create]
  end
  # usersのパス
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # コメント
  validates :text, presence: true
  # user テーブル
  belongs_to :user
  # protoype テーブル
  belongs_to :prototype
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  # プロトタイプの名称
  validates :title, presence: true
  # キャッチコピー
  validates  :catch_copy, presence: true
  # コンセプト
  validates  :concept, presence: true
  # プロトタイプの画像1枚
  has_one_attached :image
  # 必須の設定
  validates :image, presence: true
  # user テーブル
  belongs_to :user
  # comments テーブル
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # ユーザー名
  validates :name, presence: true
  # プロフィール
  validates :profile, presence: true
  # 所属
  validates :occupation, presence: true
  # 役職
  validates :position, presence: true
  # protoypes テーブル
  has_many :prototypes, dependent: :destroy
  # comments テーブル
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private def configure_permitted_parameters
    # deviseのUserモデルにパラメーターを許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:profile,:occupation,:position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # createアクション
  def create
    # データ保存の準備
    @comment = Comment.new(comment_params)
    # データ保存＆確認
    if @comment.save
      # 正常の場合、詳細ページにリダイレクト
      redirect_to prototype_path(@comment.prototype) 
    else
      # 異常の場合、詳細ページを再表示
      # prototypeの再設定
      @prototype = @comment.prototype
      # コメント一覧の再設定
      @comments = @prototype.comments
      # 詳細ページを再表示
      render "prototypes/show"
    end
  end

  # ストロングパラメーターを取得
  private def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  # ログイン確認。初期表示、詳細以外は、ログイン画面へ遷移する
  before_action :authenticate_user!, except: [:index, :show]

  # indexアクション
  def index
    @prototypes = Prototype.all
  end

  # newアクション
  def new
    # Prototypeモデルの新規オブジェクトを代入
    @prototype = Prototype.new
  end

  # createアクション
  def create
    # データ保存の準備
    @prototype = Prototype.new(prototype_params)
    # データ保存＆確認
    if @prototype.save
      # 正常の場合、ルートパスに戻る
      redirect_to root_path
    else
      # 異常の場合、投稿ページを再表示
      render :new
    end
  end

  # showアクション
  def show
    # 送信されたIDでprototypeを取得
    @prototype = Prototype.find(params[:id])
    # Commentモデルの新規オブジェクトを代入
    @comment = Comment.new
    # コメント一覧を取得
    @comments = @prototype.comments.includes(:user)
  end

  # editアクション
  def edit
    # 送信されたIDでprototypeを取得
    @prototype = Prototype.find(params[:id])
    # プロトタイプの投稿者とログインしているユーザーが違う場合
    unless user_signed_in? && current_user.id == @prototype.user_id
      # トップページに遷移する
      redirect_to action: :index
    end
  end

  # updateアクション
  def update
    # データ取得
    @prototype = Prototype.find(params[:id])
    # データ保存＆確認
    if @prototype.update(prototype_params)
      # 正常の場合、詳細ページに戻る
      redirect_to prototype_path(@prototype.id)
    else
      # 異常の場合、編集ページを再表示
      render :edit
    end
  end

  # destroyアクション
  def destroy
    # データ取得
    prototype = Prototype.find(params[:id])
    # データ削除
    prototype.destroy
    # トップページに戻る
    redirect_to root_path
  end

  # ストロングパラメーター取得
  private def prototype_params
    params.require(:prototype).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # showアクション
  def show
    # ユーザー情報取得
    @user = User.find(params[:id])
    # ユーザーに紐づくプロダクトを取得
    @prototypes = @user.prototypes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ProtoSpace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
          <%# ログインしているときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete , class: :nav__logout %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <% else %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
           <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with(model: prototype, local: true) do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%# 画像 %>
  <%= link_to image_tag(prototype.image, class: :card__img ), prototype_path(prototype) %>
  <div class="card__body">
    <%# プロトタイプ名 %>
    <%= link_to prototype.title, prototype_path(prototype), class: :card__title%>
    <p class="card__summary">
      <%# キャッチコピー %>
      <%= prototype.catch_copy %>
    </p>
    <%# 投稿者 %>
    <%= link_to "by #{prototype.user.name}", user_path(prototype.user_id), class: :card__user %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
  <% if user_signed_in? %>
    <%# ログインしているときは以下を表示する %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.name}さん", user_path(current_user.id), class: :greeting__link %>
      </div>
    <%# // ログインしているときは上記を表示する %>
    <% end %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
      <%= render partial: "prototype", collection: @prototypes %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%# プロトタイプのタイトル %>
        <%= @prototype.title %>
      </p>
      <%# プロトタイプの投稿者 %>
      <%= link_to "by #{@prototype.user.name}",  user_path(@prototype.user_id), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
          <div class="prototype__manage">
            <%= link_to "編集する", edit_prototype_path(@prototype.id), class: :prototype__btn %>
            <%= link_to "削除する", prototype_path(@prototype.id), method: :delete , class: :prototype__btn %>
          </div>
        <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <% end %>
      <div class="prototype__image">
        <%# プロトタイプの画像 %>
        <%= image_tag @prototype.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%# プロトタイプのキャッチコピー %>
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%# プロトタイプのコンセプト %>
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
          <%= form_with(model: [@prototype, @comment], local: true) do |f| %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn %>
            </div>
          <% end %> 
        <%# // ログインしているユーザーには上記を表示する %>
        <% end %>
        <%# コメント有無確認 %>
        <% if @comments %>
          <ul class="comments_lists">
            <% @comments.each do |comment| %>
              <%# 投稿に紐づくコメントを一覧する処理を記述する %>
                <li class="comments_list">
                  <%# コメントのテキスト %>
                  <%= comment.text %>
                  <%# ユーザー名 %>
                  <%= link_to "（#{comment.user.name}）", user_path(comment.user_id), class: :comment_user %>
                </li>
              <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: "prototypes/prototype", collection: @prototypes %>
      </div>
    </div>
  </div>
</div>